name = "GridapMakie"
uuid = "41f30b06-6382-4b60-a5f7-79d86b35bf5d"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu> and contributors", "Jan Weidner <jw3126@gmail.com>"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"

[compat]
julia = "1.4"

[extras]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Makie"]
